# Generated by Django 3.2.5 on 2021-07-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pizza_toppingsarray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppingsarray',
            new_name='toppings_array',
        ),
    ]
